# Generated by Django 2.2.2 on 2020-09-02 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomes', '0002_auto_20200830_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='autor_nome',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
